version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: blog-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: super_mega_secret_pasword
      MYSQL_DATABASE: blog_db
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: abcd1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
