import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header, ModalsContainer } from "@/components";
import { FiltersContextProvider, ModalsHandlersProvider } from "@/contexts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ModalsHandlersProvider>
          <ModalsContainer>
            <FiltersContextProvider>
              <Header />

              {children}
            </FiltersContextProvider>
          </ModalsContainer>
        </ModalsHandlersProvider>
      </body>
    </html>
  );
}
