import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header, Initializer, ModalsContainer } from "@/components";
import { FiltersContextProvider, ModalsHandlersProvider } from "@/contexts";
import "./globals.css";
import { ReduxProvider } from "@/redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ReduxProvider>
          <Initializer>
            <ModalsHandlersProvider>
              <ModalsContainer>
                <FiltersContextProvider>
                  <Header />

                  {children}
                </FiltersContextProvider>
              </ModalsContainer>
            </ModalsHandlersProvider>
          </Initializer>
        </ReduxProvider>
      </body>
    </html>
  );
}
